"use client";
export type Lift={name:string;unit:'lb'|'kg'|'bodyweight';sets:{reps:number|null;weight:number|null;seconds:number|null}[]};
export function StrengthEditor({value,onChange,history}:{value:Lift[];onChange:(v:Lift[])=>void;history:any[]}){
const patch=(i:number,change:Partial<Lift>)=>onChange(value.map((x,j)=>i===j?{...x,...change}:x));
const names=Array.from(new Set(history.flatMap(x=>(x.data.lifts||[]).map((l:Lift)=>l.name)))).sort() as string[];
return <section className="strength-editor"><div className="section-heading"><h3>Exercises & sets</h3><span className="muted">Actual work completed</span></div><datalist id="exercise-names">{names.map(n=><option key={n} value={n}/>)}</datalist>
{value.map((lift,i)=>{const previous=history.find(w=>(w.data.lifts||[]).some((l:Lift)=>l.name.trim().toLowerCase()===lift.name.trim().toLowerCase()&&l.unit===lift.unit));const last:Lift|undefined=previous?.data.lifts?.find((l:Lift)=>l.name.trim().toLowerCase()===lift.name.trim().toLowerCase()&&l.unit===lift.unit);
return <div className="lift-card" key={i}><div className="lift-heading"><label>Exercise<input list="exercise-names" required maxLength={120} value={lift.name} onChange={e=>patch(i,{name:e.target.value})} placeholder="e.g. Dumbbell bench press"/></label><label>Load unit<select value={lift.unit} onChange={e=>patch(i,{unit:e.target.value as Lift['unit']})}><option value="lb">lb</option><option value="kg">kg</option><option value="bodyweight">Bodyweight</option></select></label></div>
{last&&<div className="previous-lift"><span>Last time · {previous.day}: {last.sets.map(s=>[s.reps!==null?s.reps+' reps':'',s.weight!==null&&last.unit!=='bodyweight'?s.weight+' '+last.unit:'',s.seconds!==null?s.seconds+' sec':''].filter(Boolean).join(' × ')).join(' / ')}</span><button className="text-button" type="button" onClick={()=>patch(i,{sets:last.sets.map(s=>({...s}))})}>Copy sets</button></div>}
<div className="set-labels"><span>Set</span><span>Reps</span><span>{lift.unit==='bodyweight'?'Load':lift.unit}</span><span>Hold sec</span><span/></div>
{lift.sets.map((s,j)=><div className="set-row" key={j}><strong>{j+1}</strong>{(['reps','weight','seconds'] as const).map(key=><input key={key} aria-label={lift.name+' set '+(j+1)+' '+key} type="number" min={key==='weight'?0:1} max={key==='weight'?2000:key==='reps'?1000:3600} step={key==='weight'?'0.5':'1'} disabled={key==='weight'&&lift.unit==='bodyweight'} placeholder="—" value={s[key]??''} onChange={e=>patch(i,{sets:lift.sets.map((x,k)=>k===j?{...x,[key]:e.target.value===''?null:+e.target.value}:x)})}/>)}<button className="icon-button" type="button" aria-label={'Remove set '+(j+1)+' from '+lift.name} onClick={()=>patch(i,{sets:lift.sets.filter((_,k)=>k!==j)})}>×</button></div>)}
<div className="button-row"><button type="button" className="text-button" disabled={lift.sets.length>=20} onClick={()=>patch(i,{sets:[...lift.sets,{reps:null,weight:null,seconds:null}]})}>+ Add set</button><button type="button" className="text-button" onClick={()=>onChange(value.filter((_,j)=>i!==j))}>Remove exercise</button></div></div>})}
<button type="button" className="secondary full" disabled={value.length>=30} onClick={()=>onChange([...value,{name:'',unit:'lb',sets:[{reps:null,weight:null,seconds:null}]}])}>+ Add exercise</button><p className="muted strength-hint">For dumbbells, record the weight of one dumbbell consistently. For holds, use seconds. Leave anything you didn’t measure blank.</p></section>}
export function LiftSummary({lifts}:{lifts:Lift[]}){return <div className="lift-summary">{lifts.map((l,i)=><div key={i}><strong>{l.name}</strong><span>{l.sets.map((s,j)=><span className="set-chip" key={j}>{s.reps!==null?s.reps+' reps':''}{s.weight!==null&&l.unit!=='bodyweight'?' · '+s.weight+' '+l.unit:''}{l.unit==='bodyweight'?' · BW':''}{s.seconds!==null?' · '+s.seconds+'s':''}</span>)}</span></div>)}</div>}

