"use client";
import {useEffect,useState} from 'react';
import {StrengthEditor,LiftSummary} from './strength';
import {Activity,ArrowUpRight,CalendarDays,Check,ChevronLeft,ChevronRight,Dumbbell,Flame,House,Plus,Settings,Timer,TrendingUp,X,Bike,BookOpen,Heart,Download} from 'lucide-react';
type Entry={id:string;kind:string;day:string;data:any};
const days=['Mon','Tue','Wed','Thu','Fri','Sat','Sun'];
const categories=['Peloton','Strength','Mobility','Outdoor','Other'];
const defaults={goal:'Build a consistent training rhythm and understand my knee response.',baseline:null as number|null,physio:'',slots:[
{id:'ride-a',day:0,title:'My Peloton workout',minutes:20,category:'Peloton',detail:'Choose a familiar, comfortable class. Keep the effort conversational. Short version: 5–10 minutes.'},
{id:'strength-a',day:2,title:'Strength + knee capacity',minutes:20,category:'Strength',detail:'Use your established physio exercises and familiar strength movements. Record sets, reps and load. Short version: one comfortable set of your usual exercises.'},
{id:'ride-b',day:4,title:'My next workout',minutes:20,category:'Peloton',detail:'Repeat a session you tolerated well. Keep this week manageable; review your response before adding more.'}]};
const dateKey=(d=new Date())=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
const shift=(d:string,n:number)=>{const x=new Date(d+'T12:00:00');x.setDate(x.getDate()+n);return dateKey(x)};
const monday=(d:string)=>shift(d,-((new Date(d+'T12:00:00').getDay()+6)%7));
const nice=(d:string)=>new Date(d+'T12:00:00').toLocaleDateString('en-CA',{month:'short',day:'numeric'});
function Icon({category}:{category:string}){return category==='Peloton'?<Bike size={24}/>:category==='Strength'?<Dumbbell size={24}/>:<Activity size={24}/>}
export default function Training(){
const [tab,setTab]=useState('Today'),[records,setRecords]=useState<Entry[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[auth,setAuth]=useState(false),[notice,setNotice]=useState(''),[modal,setModal]=useState(''),[busy,setBusy]=useState(false),[week,setWeek]=useState(''),[today,setToday]=useState(''),[form,setForm]=useState<any>({}),[entryId,setEntryId]=useState(''),[entryDay,setEntryDay]=useState(''),[settings,setSettings]=useState<any>(defaults),[timer,setTimer]=useState(0),[running,setRunning]=useState(false);
useEffect(()=>{const d=dateKey();setToday(d);setWeek(monday(d));refresh()},[]);
useEffect(()=>{if(!running)return;const id=setInterval(()=>setTimer(n=>n+1),1000);return()=>clearInterval(id)},[running]);
useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!busy)setModal('')};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[busy]);
async function refresh(){setLoading(true);try{const r=await fetch('/api/records');const b:any=await r.json();setAuth(r.status===401);if(!r.ok)throw Error(b.error);setRecords(b.records);setError('')}catch(e:any){setError(e.message)}finally{setLoading(false)}}
const config=records.find(x=>x.kind==='settings')?.data||defaults;
const workouts=records.filter(x=>x.kind==='workout');
const weekly=workouts.filter(x=>x.day>=week&&x.day<=shift(week,6));
const checkin=records.find(x=>x.kind==='checkin'&&x.day===today);
const nextday=workouts.filter(x=>x.day<today&&x.day>=shift(today,-3)&&x.data.next===null);
const todayIndex=today?(new Date(today+'T12:00:00').getDay()+6)%7:0;
const nextSlot=config.slots.find((s:any)=>s.day>=todayIndex)||config.slots[0];
const checkText=!checkin?'Check in before you choose your effort.':checkin.data.swelling==='Severe'?'Significant symptoms: pause and seek clinical advice.':checkin.data.response==='Worse'||['Moderate'].includes(checkin.data.swelling)?'A change to notice. Keep today gentle and consider modifying your session.':'Use a familiar session and notice how your knee responds.';
function log(slot?:any,entry?:Entry){setError('');setEntryId(entry?.id||crypto.randomUUID());setEntryDay(entry?.day||today);setForm(entry?{...entry.data,lifts:entry.data.lifts||[]}: {title:slot?.title||'',category:slot?.category||'Peloton',minutes:slot?.minutes||20,effort:4,before:checkin?.data.pain??null,after:null,next:null,swelling:'Not recorded',exercises:'',lifts:[],notes:'',url:'',planId:slot?.id||''});setModal('workout')}
function repeat(entry:Entry){log(undefined,entry);setEntryId(crypto.randomUUID());setEntryDay(today);setForm({...entry.data,lifts:(entry.data.lifts||[]).map((l:any)=>({...l,sets:l.sets.map((s:any)=>({...s}))})),before:checkin?.data.pain??null,after:null,next:null,swelling:'Not recorded',notes:''});}
function openCheck(){setEntryId(checkin?.id||crypto.randomUUID());setEntryDay(today);setForm(checkin?.data||{pain:0,swelling:'None',response:'Unsure',notes:''});setModal('checkin');setError('')}
function openSettings(){setSettings(JSON.parse(JSON.stringify(config)));setModal('settings');setError('')}
async function save(kind:string,data:any,id=entryId,day=entryDay){setBusy(true);setError('');try{const r=await fetch('/api/records',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,kind,day,data})});const b:any=await r.json();if(!r.ok)throw Error(b.error);await refresh();setModal('');setNotice('Saved to your training journal.');setTimeout(()=>setNotice(''),4500)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
function exportData(){const url=URL.createObjectURL(new Blob([JSON.stringify({exportedAt:new Date().toISOString(),records},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='capacity-training-'+today+'.json';a.click();URL.revokeObjectURL(url)}
const totalMinutes=weekly.reduce((s,x)=>s+x.data.minutes,0);
const update=(key:string,value:any)=>setForm((f:any)=>({...f,[key]:value}));
return <div className="app-shell">
<aside className="sidebar"><a className="brand" href="/" aria-label="Capacity home"><span className="brand-mark"><Activity/></span>CAPACITY<span className="brand-period">.</span></a><div className="side-label">YOUR TRAINING SPACE</div><nav>{[['Today',House],['Week',CalendarDays],['Journal',BookOpen],['Progress',TrendingUp]].map(([name,I]:any)=><button key={name} className={tab===name?'nav-item active':'nav-item'} onClick={()=>setTab(name)}><I size={20}/>{name}</button>)}</nav><div className="side-bottom"><div className="side-note"><span>THE LONG GAME</span><p>Make room for<br/>getting stronger.</p><div className="small-bars"><i/><i/><i/><i/><i/></div></div><button className="nav-item" onClick={openSettings}><Settings size={19}/>Your plan & guidance</button><div className="profile"><span>DB</span><div>David Beleznay<small>Personal training</small></div></div></div></aside>
<div className="workspace"><header className="topbar"><span>PERSONAL / TRAINING</span><div><span className="private-label">Private workspace</span><button className="icon-button" aria-label="Your settings" onClick={openSettings}><Settings size={20}/></button></div></header>
<main><div className="page-heading"><div><div className="eyebrow">{today?new Date(today+'T12:00:00').toLocaleDateString('en-CA',{weekday:'long',month:'long',day:'numeric'}):'YOUR TRAINING'}</div><h1>{tab==='Today'?'Find your rhythm.':tab==='Week'?'Make space to move.':tab==='Journal'?'Every session tells you something.':'See what’s building.'}</h1><p>{tab==='Today'?'A manageable session. A quick check-in. Keep it going.':tab==='Week'?'A flexible plan around your life, with room to recover.':tab==='Journal'?'Workouts, knee response, and the details worth remembering.':'Consistency and recovery, viewed together.'}</p></div><button className="primary" onClick={()=>log()}><Plus size={20}/>Log workout</button></div>
{notice&&<div className="notice" role="status"><Check size={18}/>{notice}</div>}
{loading&&<p role="status">Loading your training journal…</p>}
{error&&!modal&&<div className="error" role="alert">{error} {auth?<a href="/signin-with-chatgpt?return_to=/" target="_top">Sign in with ChatGPT</a>:<button onClick={refresh}>Retry</button>}</div>}
{tab==='Today'&&<><div className="today-grid"><section className="session-card"><div className="card-top"><span className="eyebrow">YOUR NEXT SESSION</span><span className="pill">{nextSlot?days[nextSlot.day]:'Choose your session'}</span></div><div className="session-icon"><Icon category={nextSlot?.category||'Other'}/></div><h2>{nextSlot?.title||'Choose a familiar workout'}</h2><p>{nextSlot?.detail||'Add a workout appointment in your plan.'}</p><div className="session-meta"><span><Timer size={17}/>{nextSlot?.minutes||20} min</span><span>Flexible starting plan</span></div><div className="session-actions"><button className="lime-button" onClick={()=>log(nextSlot)}>Log this session <ArrowUpRight size={19}/></button><button className="dark-link" onClick={()=>setTab('Week')}>View week</button></div><div className="session-foot">Short on time? Your 5–10 minute version still counts.</div></section>
<section className="knee-card"><div className="card-top"><span className="eyebrow">KNEE CHECK-IN</span><Heart size={20}/></div><h2>{checkin?'Today’s signals':'How’s your knee today?'}</h2><p>{checkText}</p>{checkin?<div className="signal-grid"><div><strong>{checkin.data.pain}<small>/10</small></strong><span>Pain</span></div><div><strong className="signal-word">{checkin.data.swelling}</strong><span>Swelling</span></div></div>:<div className="signal-empty"><Activity size={35}/><span>No check-in yet<br/><small>About 20 seconds</small></span></div>}<button className="secondary full" onClick={openCheck}>{checkin?'Update check-in':'Check in'}<ChevronRight size={18}/></button><small className="muted">Signals to help you reflect, not a medical clearance.</small></section></div>
<section className="week-strip"><div><span className="eyebrow">THIS WEEK</span><strong>{workouts.filter(x=>x.day>=monday(today||dateKey())&&x.day<=shift(monday(today||dateKey()),6)).length}<small> sessions logged</small></strong></div><div className="day-strip">{days.map((d,i)=>{const day=shift(monday(today||dateKey()),i);const done=workouts.some(x=>x.day===day);const planned=config.slots.some((s:any)=>s.day===i);return <button key={d} className={'day '+(day===today?'current ':'')+(done?'done':'')} onClick={()=>{setWeek(monday(today));setTab('Week')}}><span>{d}</span><b>{done?<Check size={18}/>:new Date(day+'T12:00:00').getDate()}</b><small>{done?'Logged':planned?'Planned':'Open'}</small></button>})}</div></section>
<div className="lower-grid"><section className="panel"><div className="section-heading"><h2>Close the loop</h2><span className="count">{nextday.length}</span></div>{nextday.length?nextday.map(x=><div className="entry-line" key={x.id}><span className="tile-icon"><Icon category={x.data.category}/></span><div><strong>{x.data.title}</strong><small>{nice(x.day)} · How did your knee feel next day?</small></div><button className="text-button" onClick={()=>log(undefined,x)}>Add response</button></div>):<div className="empty-inline"><Check size={22}/><p>No next-day responses waiting.<small>After a workout, add your knee response here.</small></p></div>}</section><section className="panel timer-panel"><div className="section-heading"><h2>Session timer</h2><Timer size={20}/></div><div className="clock">{String(Math.floor(timer/60)).padStart(2,'0')}<span>:</span>{String(timer%60).padStart(2,'0')}</div><div className="button-row"><button className="secondary" onClick={()=>setRunning(!running)}>{running?'Pause':'Start'}</button><button className="text-button" onClick={()=>{setRunning(false);setTimer(0)}}>Reset</button></div><small className="muted">For timing sets or rest. Follow your own prescription.</small></section></div></>}
{tab==='Week'&&<><div className="section-heading week-controls"><button className="icon-button" aria-label="Previous week" onClick={()=>setWeek(shift(week,-7))}><ChevronLeft/></button><h2>{nice(week)} – {nice(shift(week,6))}</h2><button className="icon-button" aria-label="Next week" onClick={()=>setWeek(shift(week,7))}><ChevronRight/></button><button className="text-button" onClick={openSettings}>Edit recurring plan</button></div><p className="plan-note">Proposed starting rhythm · Adapt the days and exercises to your baseline and physio’s advice.</p><div className="week-list">{days.map((day,i)=>{const d=shift(week,i);const slots=config.slots.filter((s:any)=>s.day===i);const logs=weekly.filter(x=>x.day===d);return <section className={'week-row '+(d===today?'today-row':'')} key={day}><div className="week-date"><span>{day}</span><strong>{new Date(d+'T12:00:00').getDate()}</strong></div><div className="week-content">{slots.length?slots.map((s:any)=><div key={s.id}><div className="workout-title"><Icon category={s.category}/><h3>{s.title}</h3><span className="pill">{s.minutes} min</span></div><p>{s.detail}</p><button className="text-button" onClick={()=>{log(s);setEntryDay(d>today?today:d)}}>Log session</button></div>):<div><h3>Open day</h3><p>Recovery, family time, or comfortable movement if it fits.</p></div>}{logs.map(x=><div className="logged-chip" key={x.id}><Check size={15}/>{x.data.title} · {x.data.minutes} min</div>)}</div></section>})}</div></>}
{tab==='Journal'&&<section className="panel"><div className="section-heading"><h2>Workout journal <span className="count">{workouts.length}</span></h2><button className="text-button" onClick={exportData}><Download size={17}/>Export data</button></div>{workouts.length?workouts.map(x=><article className="journal-entry" key={x.id}><div className="entry-line"><span className="tile-icon"><Icon category={x.data.category}/></span><div><small>{nice(x.day)} · {x.data.category}</small><h3>{x.data.title}</h3></div><button className="text-button" onClick={()=>repeat(x)}>Repeat</button><button className="text-button" onClick={()=>log(undefined,x)}>Edit</button></div><div className="journal-metrics"><span>{x.data.minutes} min</span><span>Effort {x.data.effort}/10</span><span>Knee {x.data.before??'—'} → {x.data.after??'—'}</span><span>Next day {x.data.next===null?'Not recorded':x.data.next+'/10'}</span></div>{x.data.lifts?.length>0&&<LiftSummary lifts={x.data.lifts}/>} {x.data.exercises&&<p className="preserve">{x.data.exercises}</p>}{x.data.notes&&<p className="preserve muted">{x.data.notes}</p>}{x.data.url&&<a href={x.data.url} target="_blank" rel="noreferrer">Open class <ArrowUpRight size={14}/></a>}</article>):<div className="empty-state"><BookOpen size={36}/><h3>Your first session starts the story.</h3><p>Log a recent workout or complete your next session. There’s no backlog to catch up on.</p><button className="primary" onClick={()=>log()}>Log a workout</button></div>}</section>}
{tab==='Progress'&&<><div className="stats-grid"><div className="stat"><span>This week</span><strong>{totalMinutes}<small> min</small></strong><p>{weekly.length} sessions logged</p></div><div className="stat"><span>Strength this week</span><strong>{weekly.filter(x=>x.data.category==='Strength').length}</strong><p>Sessions, at your own pace</p></div><div className="stat"><span>Next-day responses</span><strong>{workouts.filter(x=>x.data.next!==null).length}<small> / {workouts.length}</small></strong><p>Learning what works for you</p></div></div><div className="lower-grid"><section className="panel"><h2>Four weeks of showing up</h2><p className="muted">Minutes logged each week. No target to chase.</p><div className="chart">{[-3,-2,-1,0].map(n=>{const w=shift(monday(today||dateKey()),n*7);const minutes=workouts.filter(x=>x.day>=w&&x.day<=shift(w,6)).reduce((a,x)=>a+x.data.minutes,0);const max=Math.max(60,...[-3,-2,-1,0].map(k=>{const t=shift(monday(today||dateKey()),k*7);return workouts.filter(x=>x.day>=t&&x.day<=shift(t,6)).reduce((a,x)=>a+x.data.minutes,0)}));return <div className="bar-column" key={n}><strong>{minutes}m</strong><div className="bar-space"><div className="bar" style={{height:Math.max(3,minutes/max*140)}}/></div><small>{nice(w)}</small></div>})}</div></section><section className="panel"><h2>Your weekly review</h2><ol className="review-list"><li><strong>Did the plan fit?</strong><p>Notice whether time, energy, knee symptoms or indecision got in the way.</p></li><li><strong>How did your knee respond?</strong><p>Compare before, after and next-day symptoms. Missing entries mean unknown.</p></li><li><strong>What is one useful adjustment?</strong><p>Repeat a manageable week. Consider changing one thing only when recovery supports it.</p></li></ol><button className="secondary" onClick={openSettings}>Adjust next week</button></section></div><section className="panel"><h2>Knee signals</h2>{records.filter(x=>x.kind==='checkin').length?records.filter(x=>x.kind==='checkin').slice(0,14).map(x=><div className="signal-row" key={x.id}><strong>{nice(x.day)}</strong><span>Pain {x.data.pain}/10</span><span>{x.data.swelling} swelling</span><span>{x.data.response}</span></div>):<p className="muted">Check in to build your own symptom history. We won’t estimate missing days.</p>}</section></>}
<footer><span>CAPACITY / Built around your life.</span><a href="https://www.nice.org.uk/guidance/NG226/chapter/recommendations" target="_blank" rel="noreferrer">Exercise & osteoarthritis guidance <ArrowUpRight size={13}/></a></footer>
</main></div>
{modal&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="modal-heading"><div><span className="eyebrow">{modal==='workout'?'TRAINING JOURNAL':modal==='checkin'?'TODAY’S SIGNALS':'PERSONALIZE'}</span><h2 id="dialog-title">{modal==='workout'?'Log your session':modal==='checkin'?'A quick knee check':'Your plan & guidance'}</h2></div><button className="icon-button" aria-label="Close" disabled={busy} onClick={()=>setModal('')}><X/></button></div>
<form onSubmit={e=>{e.preventDefault();modal==='settings'?save('settings',settings,'settings',today):save(modal,form)}}>
{modal==='workout'&&<><div className="form-grid"><label>Workout name<input autoFocus required maxLength={120} value={form.title} onChange={e=>update('title',e.target.value)} placeholder="e.g. 20 min low impact ride"/></label><label>Date<input required type="date" max={today} value={entryDay} onChange={e=>setEntryDay(e.target.value)}/></label><label>Workout type<select value={form.category} onChange={e=>update('category',e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Minutes<input required type="number" min="1" max="600" value={form.minutes} onChange={e=>update('minutes',+e.target.value)}/></label></div><label>Effort · {form.effort}/10<input type="range" min="1" max="10" value={form.effort} onChange={e=>update('effort',+e.target.value)}/><span className="range-labels"><small>Very easy</small><small>Maximum effort</small></span></label><div className="form-divider">Knee response <span>Leave blank if not recorded</span></div><div className="form-grid three">{[['before','Before'],['after','After'],['next','Next day']].map(([key,label])=><label key={key}>{label} · pain /10<input type="number" min="0" max="10" value={form[key]??''} placeholder="—" onChange={e=>update(key,e.target.value===''?null:+e.target.value)}/></label>)}</div><label>Swelling after session<select value={form.swelling} onChange={e=>update('swelling',e.target.value)}>{['Not recorded','None','Mild','Moderate','Severe'].map(x=><option key={x}>{x}</option>)}</select></label><StrengthEditor value={form.lifts||[]} onChange={v=>update('lifts',v)} history={workouts.filter(x=>x.id!==entryId&&x.day<=entryDay)}/><details open={false}><summary>Class link & additional exercise notes</summary><label>Additional exercise notes<textarea maxLength={4000} value={form.exercises} onChange={e=>update('exercises',e.target.value)} placeholder={'Exercise · sets × reps · weight / hold time\nUse your existing exercise prescription.'}/></label><label>Peloton or workout link<input type="url" pattern="https://.*" value={form.url} onChange={e=>update('url',e.target.value)} placeholder="https://…"/></label></details><label>Notes<textarea maxLength={4000} value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="What felt good? Anything you changed?"/></label></>}
{modal==='checkin'&&<><p className="muted">Record what you notice. Compare with your usual symptoms.</p><label>Pain now · {form.pain}/10<input autoFocus type="range" min="0" max="10" value={form.pain} onChange={e=>update('pain',+e.target.value)}/><span className="range-labels"><small>No pain</small><small>Worst pain</small></span></label><label>Swelling<select value={form.swelling} onChange={e=>update('swelling',e.target.value)}>{['None','Mild','Moderate','Severe'].map(x=><option key={x}>{x}</option>)}</select></label><label>Compared with your usual knee symptoms<select value={form.response} onChange={e=>update('response',e.target.value)}>{['Unsure','Usual','Better','Worse'].map(x=><option key={x}>{x}</option>)}</select></label><label>Anything else?<textarea maxLength={4000} value={form.notes} onChange={e=>update('notes',e.target.value)} placeholder="Stiffness, confidence, recent activity…"/></label><p className="guidance">New or significant swelling, locking, buckling or rapidly changing symptoms deserve clinical advice. This check-in does not diagnose or clear you to train.</p></>}
{modal==='settings'&&<><label>What you’re working toward<textarea autoFocus maxLength={500} value={settings.goal} onChange={e=>setSettings({...settings,goal:e.target.value})}/></label><label>Usual knee pain /10 · optional<input type="number" min="0" max="10" value={settings.baseline??''} onChange={e=>setSettings({...settings,baseline:e.target.value===''?null:+e.target.value})}/></label><label>Physio guidance, exercises & restrictions<textarea maxLength={4000} value={settings.physio} onChange={e=>setSettings({...settings,physio:e.target.value})} placeholder="Your current prescribed exercises, dosage, restrictions and review date."/></label><div className="form-divider">Recurring workout appointments</div>{settings.slots.map((s:any,i:number)=><div className="slot-editor" key={s.id}><div className="form-grid"><label>Day<select value={s.day} onChange={e=>setSettings({...settings,slots:settings.slots.map((x:any,j:number)=>j===i?{...x,day:+e.target.value}:x)})}>{days.map((d,k)=><option value={k} key={d}>{d}</option>)}</select></label><label>Minutes<input type="number" min="5" max="180" required value={s.minutes} onChange={e=>setSettings({...settings,slots:settings.slots.map((x:any,j:number)=>j===i?{...x,minutes:+e.target.value}:x)})}/></label></div><label>Session<input required maxLength={120} value={s.title} onChange={e=>setSettings({...settings,slots:settings.slots.map((x:any,j:number)=>j===i?{...x,title:e.target.value}:x)})}/></label><label>Type<select value={s.category} onChange={e=>setSettings({...settings,slots:settings.slots.map((x:any,j:number)=>j===i?{...x,category:e.target.value}:x)})}>{categories.map(x=><option key={x}>{x}</option>)}</select></label><label>Session instructions & short version<textarea maxLength={1500} value={s.detail} onChange={e=>setSettings({...settings,slots:settings.slots.map((x:any,j:number)=>j===i?{...x,detail:e.target.value}:x)})}/></label><button type="button" className="text-button" onClick={()=>setSettings({...settings,slots:settings.slots.filter((_:any,j:number)=>i!==j)})}>Remove appointment</button></div>)}<button type="button" className="secondary" disabled={settings.slots.length>=14} onClick={()=>setSettings({...settings,slots:[...settings.slots,{id:crypto.randomUUID(),day:5,title:'My workout',minutes:20,category:'Other',detail:''}]})}><Plus size={17}/>Add appointment</button><p className="guidance">The starting schedule is a proposal, not an individualized exercise prescription. Use your current clinical advice to choose movements and loads.</p></>}
{error&&<div className="error" role="alert">{error}{auth&&<a href="/signin-with-chatgpt?return_to=/" target="_top"> Sign in with ChatGPT</a>}</div>}
<div className="modal-actions"><button className="secondary" type="button" disabled={busy} onClick={()=>setModal('')}>Cancel</button><button className="primary" disabled={busy||loading} type="submit">{busy?'Saving…':'Save '+(modal==='workout'?'session':modal==='checkin'?'check-in':'plan')}<Check size={18}/></button></div></form></section></div>}
</div>
}


