import {getChatGPTUser} from '../../chatgpt-auth';
import {database} from '../../../lib/db';
import {z} from 'zod';
const base=z.object({id:z.string().min(1).max(200),kind:z.enum(['workout','checkin','settings']),day:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),data:z.record(z.unknown())});
const pain=z.number().min(0).max(10).nullable();
const lift=z.object({name:z.string().trim().min(1).max(120),unit:z.enum(['lb','kg','bodyweight']),sets:z.array(z.object({reps:z.number().int().min(1).max(1000).nullable(),weight:z.number().min(0).max(2000).nullable(),seconds:z.number().int().min(1).max(3600).nullable()})).min(1).max(20)});
const workout=z.object({lifts:z.array(lift).max(30).optional(),title:z.string().min(1).max(120),category:z.enum(['Peloton','Strength','Mobility','Outdoor','Other']),minutes:z.number().int().min(1).max(600),effort:z.number().int().min(1).max(10),before:pain,after:pain,next:pain,swelling:z.enum(['Not recorded','None','Mild','Moderate','Severe']),notes:z.string().max(4000),exercises:z.string().max(4000),url:z.string().max(1000).refine(v=>!v||/^https:\/\//.test(v)),planId:z.string().max(50).optional()});
const checkin=z.object({pain:z.number().int().min(0).max(10),swelling:z.enum(['None','Mild','Moderate','Severe']),response:z.enum(['Usual','Better','Worse','Unsure']),notes:z.string().max(4000)});
const settings=z.object({goal:z.string().max(500),physio:z.string().max(4000),baseline:pain,slots:z.array(z.object({id:z.string().max(50),day:z.number().int().min(0).max(6),title:z.string().min(1).max(120),minutes:z.number().int().min(5).max(180),category:z.enum(['Peloton','Strength','Mobility','Outdoor','Other']),detail:z.string().max(1500)})).max(14)});
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to load your workouts.'},{status:401});try{const r=await database().prepare('SELECT id,kind,day,payload FROM records WHERE owner = ? ORDER BY day DESC, rowid DESC').bind(user.userId).all();return Response.json({records:r.results.map((r:any)=>({id:r.id,kind:r.kind,day:r.day,data:JSON.parse(r.payload)}))},{headers:{'Cache-Control':'no-store'}})}catch(e){console.error(e);return Response.json({error:'Could not load your training data. Please try again.'},{status:503})}}
export async function POST(request:Request){const user=await getChatGPTUser();if(!user)return Response.json({error:'Sign in to save your workouts.'},{status:401});if(request.headers.get('origin')!==new URL(request.url).origin)return Response.json({error:'Invalid origin'},{status:403});try{const raw=await request.text();if(raw.length>25000)return Response.json({error:'Entry is too long.'},{status:400});const r=base.parse(JSON.parse(raw));const data=(r.kind==='workout'?workout:r.kind==='checkin'?checkin:settings).parse(r.data);const id=r.id.startsWith(user.userId+':')?r.id:user.userId+':'+(r.kind==='settings'?'settings':r.id);await database().prepare('INSERT INTO records (id,owner,kind,day,payload) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET kind=excluded.kind,day=excluded.day,payload=excluded.payload WHERE records.owner=excluded.owner').bind(id,user.userId,r.kind,r.day,JSON.stringify(data)).run();return Response.json({ok:true});}catch(e){if(e instanceof z.ZodError||e instanceof SyntaxError)return Response.json({error:'Please check the fields and try again.'},{status:400});console.error(e);return Response.json({error:'Save failed. Your entry is still here; please retry.'},{status:503})}}


